###  Dataset Loading:

In [2]:
import pandas as pd
zomato_df = pd.read_csv("../data/zomato.csv", encoding='latin-1')
country_df = pd.read_csv("../data/Country-Code.csv")

zomato_df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
df = zomato_df.merge(country_df, how='left', on='Country Code')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

### Cleaning Steps:

In [4]:
columns_to_drop = ['    Restaurant ID', 'Address', 'Locality', 'Locality Verbose',
                'Switch to order menu', 'Currency', 'Rating color', 'Rating text']
df.drop(columns=columns_to_drop, inplace=True)

In [5]:
df.columns.tolist()

['Restaurant Name',
 'Country Code',
 'City',
 'Longitude',
 'Latitude',
 'Cuisines',
 'Average Cost for two',
 'Has Table booking',
 'Has Online delivery',
 'Is delivering now',
 'Price range',
 'Aggregate rating',
 'Votes',
 'Country']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9551 non-null   object
 1   Country Code          9551 non-null   int64
 2   City                  9551 non-null   object
 3   Longitude             9551 non-null   float64
 4   Latitude              9551 non-null   float64
 5   Cuisines              9542 non-null   object
 6   Average Cost for two  9551 non-null   int64
 7   Has Table booking     9551 non-null   object
 8   Has Online delivery   9551 non-null   object
 9   Is delivering now     9551 non-null   object
 10  Price range           9551 non-null   int64
 11  Aggregate rating      9551 non-null   float64
 12  Votes                 9551 non-null   int64
 13  Country               9551 non-null   object
dtypes: float64(3), int64(4), object(7)
memory usage: 1.0+ MB

In [7]:
df.duplicated().sum()

3

In [8]:
df.drop_duplicates(inplace = True)
df.duplicated().sum()

0

In [9]:
df.isna().sum()

Restaurant Name         0
Country Code            0
City                    0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Price range             0
Aggregate rating        0
Votes                   0
Country                 0
dtype: int64

In [10]:
df.dropna(inplace=True)
df.isna().sum()

Restaurant Name         0
Country Code            0
City                    0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Price range             0
Aggregate rating        0
Votes                   0
Country                 0
dtype: int64

In [11]:
df['Cuisines'] = df['Cuisines'].str.lower().str.strip()

### Feature Engineering:

In [12]:
df['Primary Cuisine'] = df['Cuisines'].apply(lambda x: x.split(',')[0].strip())
df

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine
0,Le Petit Souffle,162,Makati City,121.027535,14.565443,"french, japanese, desserts",1100,Yes,No,No,3,4.8,314,Phillipines,french
1,Izakaya Kikufuji,162,Makati City,121.014101,14.553708,japanese,1200,Yes,No,No,3,4.5,591,Phillipines,japanese
2,Heat - Edsa Shangri-La,162,Mandaluyong City,121.056831,14.581404,"seafood, asian, filipino, indian",4000,Yes,No,No,4,4.4,270,Phillipines,seafood
3,Ooma,162,Mandaluyong City,121.056475,14.585318,"japanese, sushi",1500,No,No,No,4,4.9,365,Phillipines,japanese
4,Sambo Kojin,162,Mandaluyong City,121.057508,14.584450,"japanese, korean",1500,Yes,No,No,4,4.8,229,Phillipines,japanese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,28.977392,41.022793,turkish,80,No,No,No,3,4.1,788,Turkey,turkish
9547,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,29.041297,41.009847,"world cuisine, patisserie, cafe",105,No,No,No,3,4.2,1034,Turkey,world cuisine
9548,Huqqa,208,ï¿½ï¿½stanbul,29.034640,41.055817,"italian, world cuisine",170,No,No,No,4,3.7,661,Turkey,italian
9549,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,29.036019,41.057979,restaurant cafe,120,No,No,No,4,4.0,901,Turkey,restaurant cafe
9550,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,29.026016,40.984776,cafe,55,No,No,No,2,4.0,591,Turkey,cafe

In [13]:
df['Average Cost for two'].describe()

count      9539.000000
mean       1200.593563
std       16131.273074
min           0.000000
25%         250.000000
50%         400.000000
75%         700.000000
max      800000.000000
Name: Average Cost for two, dtype: float64

In [14]:
q1 = df['Average Cost for two'].quantile(0.25)
q3 = df['Average Cost for two'].quantile(0.75)

iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

df = df[
    (df['Average Cost for two'] >= lower_bound) &
    (df['Average Cost for two'] <= upper_bound)
]

print(df['Average Cost for two'].describe())

count    8686.000000
mean      438.321667
std       281.909101
min         0.000000
25%       250.000000
50%       400.000000
75%       600.000000
max      1350.000000
Name: Average Cost for two, dtype: float64

In [15]:
df = df[df['Average Cost for two'] > 0]

###### | Low    | 0 – 250    |
###### | Medium | 251 – 600  |
###### | High   | 601 – 1350 |

In [16]:
def cost_category(cost):
    if cost <= 250:
        return 'Low'
    elif cost <= 600:
        return 'Medium'
    else:
        return 'High'

df['Cost Category'] = df['Average Cost for two'].apply(cost_category)
df

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine,Cost Category
0,Le Petit Souffle,162,Makati City,121.027535,14.565443,"french, japanese, desserts",1100,Yes,No,No,3,4.8,314,Phillipines,french,High
1,Izakaya Kikufuji,162,Makati City,121.014101,14.553708,japanese,1200,Yes,No,No,3,4.5,591,Phillipines,japanese,High
5,Din Tai Fung,162,Mandaluyong City,121.056314,14.583764,chinese,1000,No,No,No,3,4.4,336,Phillipines,chinese,High
9,Locavore,162,Pasig City,121.056532,14.572041,filipino,1100,Yes,No,No,3,4.8,532,Phillipines,filipino,High
10,Silantro Fil-Mex,162,Pasig City,121.057916,14.567689,"filipino, mexican",800,No,No,No,3,4.9,1070,Phillipines,filipino,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,28.977392,41.022793,turkish,80,No,No,No,3,4.1,788,Turkey,turkish,Low
9547,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,29.041297,41.009847,"world cuisine, patisserie, cafe",105,No,No,No,3,4.2,1034,Turkey,world cuisine,Low
9548,Huqqa,208,ï¿½ï¿½stanbul,29.034640,41.055817,"italian, world cuisine",170,No,No,No,4,3.7,661,Turkey,italian,Low
9549,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,29.036019,41.057979,restaurant cafe,120,No,No,No,4,4.0,901,Turkey,restaurant cafe,Low
9550,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,29.026016,40.984776,cafe,55,No,No,No,2,4.0,591,Turkey,cafe,Low

In [17]:
df.columns.tolist()

['Restaurant Name',
 'Country Code',
 'City',
 'Longitude',
 'Latitude',
 'Cuisines',
 'Average Cost for two',
 'Has Table booking',
 'Has Online delivery',
 'Is delivering now',
 'Price range',
 'Aggregate rating',
 'Votes',
 'Country',
 'Primary Cuisine',
 'Cost Category']

In [18]:
df.to_csv("../data/clean_df.csv", index=False)

In [19]:
clean_df = pd.read_csv("../data/clean_df.csv")
clean_df.head()

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine,Cost Category
0,Le Petit Souffle,162,Makati City,121.027535,14.565443,"french, japanese, desserts",1100,Yes,No,No,3,4.8,314,Phillipines,french,High
1,Izakaya Kikufuji,162,Makati City,121.014101,14.553708,japanese,1200,Yes,No,No,3,4.5,591,Phillipines,japanese,High
2,Din Tai Fung,162,Mandaluyong City,121.056314,14.583764,chinese,1000,No,No,No,3,4.4,336,Phillipines,chinese,High
3,Locavore,162,Pasig City,121.056532,14.572041,filipino,1100,Yes,No,No,3,4.8,532,Phillipines,filipino,High
4,Silantro Fil-Mex,162,Pasig City,121.057916,14.567689,"filipino, mexican",800,No,No,No,3,4.9,1070,Phillipines,filipino,High

In [20]:
unique_countries = sorted(df['Country'].dropna().unique().tolist())

unique_cities = sorted(df['City'].dropna().unique().tolist())

unique_cuisines = sorted(df['Primary Cuisine'].dropna().unique().tolist())

unique_cost_categories = sorted(df['Cost Category'].dropna().unique().tolist())

print("Countries:", unique_countries)
print("Cities:", unique_cities)
print("Cuisines:", unique_cuisines)
print("Budgets:", unique_cost_categories)

Countries: ['Australia', 'Brazil', 'Canada', 'India', 'New Zealand', 'Phillipines', 'Qatar', 'Singapore', 'South Africa', 'Sri Lanka', 'Turkey', 'UAE', 'United Kingdom', 'United States']
Cities: ['Abu Dhabi', 'Agra', 'Ahmedabad', 'Albany', 'Allahabad', 'Amritsar', 'Ankara', 'Armidale', 'Athens', 'Auckland', 'Augusta', 'Aurangabad', 'Balingup', 'Bangalore', 'Beechworth', 'Bhopal', 'Bhubaneshwar', 'Birmingham', 'Boise', 'Brasï¿½_lia', 'Cape Town', 'Cedar Rapids/Iowa City', 'Chandigarh', 'Chatham-Kent', 'Chennai', 'Clatskanie', 'Cochrane', 'Coimbatore', 'Colombo', 'Columbus', 'Consort', 'Dalton', 'Davenport', 'Dehradun', 'Des Moines', 'Dicky Beach', 'Doha', 'Dubai', 'Dubuque', 'East Ballina', 'Edinburgh', 'Faridabad', 'Fernley', 'Flaxton', 'Forrest', 'Gainesville', 'Ghaziabad', 'Goa', 'Gurgaon', 'Guwahati', 'Hepburn Springs', 'Huskisson', 'Hyderabad', 'Indore', 'Inner City', 'Inverloch', 'Jaipur', 'Johannesburg', 'Kanpur', 'Kochi', 'Kolkata', 'Lakes Entrance', 'Lakeview', 'Lincoln', 'London', 'Lorn', 'Lucknow', 'Ludhiana', 'Macedon', 'Macon', 'Makati City', 'Manchester', 'Mandaluyong City', 'Mangalore', 'Mayfield', 'Mc Millan', 'Middleton Beach', 'Mohali', 'Monroe', 'Montville', 'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'New Delhi', 'Noida', 'Ojo Caliente', 'Orlando', 'Palm Cove', 'Pasig City', 'Patna', 'Paynesville', 'Penola', 'Pensacola', 'Phillip Island', 'Pocatello', 'Potrero', 'Pretoria', 'Princeton', 'Puducherry', 'Pune', 'Quezon City', 'Ranchi', 'Randburg', 'Rest of Hawaii', 'Rio de Janeiro', 'San Juan City', 'Sandton', 'Santa Rosa', 'Savannah', 'Secunderabad', 'Sharjah', 'Singapore', 'Sioux City', 'Surat', 'Sï¿½ï¿½o Paulo', 'Tagaytay City', 'Taguig City', 'Tampa Bay', 'Tanunda', 'Trentham East', 'Vadodara', 'Valdosta', 'Varanasi', 'Vernonia', 'Victor Harbor', 'Vineland Station', 'Vizag', 'Waterloo', 'Weirton', 'Wellington City', 'Winchester Bay', 'Yorkton', 'ï¿½ï¿½stanbul']
Cuisines: ['afghani', 'african', 'american', 'andhra', 'arabian', 'argentine', 'asian', 'asian fusion', 'assamese', 'australian', 'awadhi', 'bakery', 'bar food', 'bbq', 'bengali', 'beverages', 'bihari', 'biryani', 'brazilian', 'breakfast', 'british', 'burger', 'burmese', 'cafe', 'cajun', 'caribbean', 'charcoal grill', 'chinese', 'coffee and tea', 'contemporary', 'continental', 'cuban', 'cuisine varies', 'desserts', 'european', 'fast food', 'filipino', 'finger food', 'french', 'german', 'goan', 'gourmet fast food', 'greek', 'grill', 'gujarati', 'hawaiian', 'healthy food', 'hyderabadi', 'ice cream', 'indian', 'international', 'irish', 'italian', 'japanese', 'juices', 'kashmiri', 'kebab', 'kerala', 'kiwi', 'korean', 'latin american', 'lebanese', 'lucknowi', 'maharashtrian', 'malaysian', 'malwani', 'mediterranean', 'mexican', 'middle eastern', 'mithai', 'modern australian', 'modern indian', 'mughlai', 'naga', 'nepalese', 'new american', 'north eastern', 'north indian', 'oriya', 'pakistani', 'parsi', 'patisserie', 'persian', 'peruvian', 'pizza', 'portuguese', 'pub food', 'rajasthani', 'ramen', 'raw meats', 'restaurant cafe', 'salad', 'sandwich', 'scottish', 'seafood', 'singaporean', 'south indian', 'southern', 'spanish', 'steak', 'street food', 'sushi', 'taiwanese', 'tapas', 'tea', 'thai', 'tibetan', 'turkish', 'turkish pizza', 'vietnamese', 'western', 'world cuisine']
Budgets: ['High', 'Low', 'Medium']