In [24]:
import pandas as pd 
df = pd.read_csv("../data/clean_df.csv")
df

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine,Cost Category
0,Le Petit Souffle,162,Makati City,121.027535,14.565443,"french, japanese, desserts",1100,Yes,No,No,3,4.8,314,Phillipines,french,High
1,Izakaya Kikufuji,162,Makati City,121.014101,14.553708,japanese,1200,Yes,No,No,3,4.5,591,Phillipines,japanese,High
2,Din Tai Fung,162,Mandaluyong City,121.056314,14.583764,chinese,1000,No,No,No,3,4.4,336,Phillipines,chinese,High
3,Locavore,162,Pasig City,121.056532,14.572041,filipino,1100,Yes,No,No,3,4.8,532,Phillipines,filipino,High
4,Silantro Fil-Mex,162,Pasig City,121.057916,14.567689,"filipino, mexican",800,No,No,No,3,4.9,1070,Phillipines,filipino,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8666,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,28.977392,41.022793,turkish,80,No,No,No,3,4.1,788,Turkey,turkish,Low
8667,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,29.041297,41.009847,"world cuisine, patisserie, cafe",105,No,No,No,3,4.2,1034,Turkey,world cuisine,Low
8668,Huqqa,208,ï¿½ï¿½stanbul,29.034640,41.055817,"italian, world cuisine",170,No,No,No,4,3.7,661,Turkey,italian,Low
8669,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,29.036019,41.057979,restaurant cafe,120,No,No,No,4,4.0,901,Turkey,restaurant cafe,Low
8670,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,29.026016,40.984776,cafe,55,No,No,No,2,4.0,591,Turkey,cafe,Low

In [25]:
def filter_restaurants(df, selected_cuisines, cost_category, selected_country):
    filtered_df = df[
        df['Primary Cuisine'].isin(selected_cuisines) &
        (df['Cost Category'] == cost_category) &
        (df['Country'] == selected_country)
    ]

    return filtered_df

In [26]:
def rank_restaurants(df):
    if df['Votes'].max() == 0:
        df['norm_votes'] = 0
    else:
        df['norm_votes'] = df['Votes'] / df['Votes'].max()

    df['norm_rating'] = df['Aggregate rating'] / 5 

    df['Score'] = (df['norm_rating'] * 0.7) + (df['norm_votes'] * 0.3)

    return df.sort_values(by='Score', ascending=False)

In [27]:
df = rank_restaurants(df)
df

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine,Cost Category,norm_votes,norm_rating,Score
696,Truffles,1,Bangalore,77.614293,12.933298,"american, burger, cafe",800,No,Yes,No,2,4.7,9667,India,american,High,1.000000,0.94,0.958000
2131,Peter Cat,1,Kolkata,88.352885,22.552672,"continental, north indian",1000,No,Yes,No,3,4.3,7574,India,continental,High,0.783490,0.86,0.837047
2669,Naturals Ice Cream,1,New Delhi,77.222148,28.634348,ice cream,150,No,Yes,No,1,4.9,2620,India,ice cream,Low,0.271025,0.98,0.767308
2727,Saravana Bhavan,1,New Delhi,77.216310,28.632358,south indian,500,No,Yes,No,2,4.3,5172,India,south indian,Medium,0.535016,0.86,0.762505
477,Bern's Steak House,216,Tampa Bay,-82.482962,27.931516,"american, desserts, steak",70,No,No,No,4,4.7,3157,United States,american,Low,0.326575,0.94,0.755972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7079,Soni Food Court,1,New Delhi,77.307644,28.590867,north indian,150,No,No,No,1,0.0,0,India,north indian,Low,0.000000,0.00,0.000000
7076,Shahi Muradabadi Chicken Biryani,1,New Delhi,77.308075,28.589743,biryani,150,No,No,No,1,0.0,0,India,biryani,Low,0.000000,0.00,0.000000
7075,Seven Star Pizza,1,New Delhi,77.305843,28.592302,pizza,400,No,No,No,1,0.0,0,India,pizza,Medium,0.000000,0.00,0.000000
7074,Rudra The Dhaba,1,New Delhi,77.306574,28.591447,north indian,200,No,No,No,1,0.0,0,India,north indian,Low,0.000000,0.00,0.000000
4763,Creamy Creation,1,New Delhi,77.309698,28.623975,bakery,300,No,No,No,1,0.0,0,India,bakery,Medium,0.000000,0.00,0.000000

In [28]:
def add_explanation(df):
    df['Explanation'] = df.apply(
        lambda row: f"Matched on {row['Primary Cuisine']} cuisine, {row['Cost Category']} budget in {row['Country']} with rating {row['Aggregate rating']}",
        axis=1
    )
    return df

In [29]:
df = add_explanation(df)
df

,Restaurant Name,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Price range,Aggregate rating,Votes,Country,Primary Cuisine,Cost Category,norm_votes,norm_rating,Score,Explanation
696,Truffles,1,Bangalore,77.614293,12.933298,"american, burger, cafe",800,No,Yes,No,2,4.7,9667,India,american,High,1.000000,0.94,0.958000,"Matched on american cuisine, High budget in In..."
2131,Peter Cat,1,Kolkata,88.352885,22.552672,"continental, north indian",1000,No,Yes,No,3,4.3,7574,India,continental,High,0.783490,0.86,0.837047,"Matched on continental cuisine, High budget in..."
2669,Naturals Ice Cream,1,New Delhi,77.222148,28.634348,ice cream,150,No,Yes,No,1,4.9,2620,India,ice cream,Low,0.271025,0.98,0.767308,"Matched on ice cream cuisine, Low budget in In..."
2727,Saravana Bhavan,1,New Delhi,77.216310,28.632358,south indian,500,No,Yes,No,2,4.3,5172,India,south indian,Medium,0.535016,0.86,0.762505,"Matched on south indian cuisine, Medium budget..."
477,Bern's Steak House,216,Tampa Bay,-82.482962,27.931516,"american, desserts, steak",70,No,No,No,4,4.7,3157,United States,american,Low,0.326575,0.94,0.755972,"Matched on american cuisine, Low budget in Uni..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7079,Soni Food Court,1,New Delhi,77.307644,28.590867,north indian,150,No,No,No,1,0.0,0,India,north indian,Low,0.000000,0.00,0.000000,"Matched on north indian cuisine, Low budget in..."
7076,Shahi Muradabadi Chicken Biryani,1,New Delhi,77.308075,28.589743,biryani,150,No,No,No,1,0.0,0,India,biryani,Low,0.000000,0.00,0.000000,"Matched on biryani cuisine, Low budget in Indi..."
7075,Seven Star Pizza,1,New Delhi,77.305843,28.592302,pizza,400,No,No,No,1,0.0,0,India,pizza,Medium,0.000000,0.00,0.000000,"Matched on pizza cuisine, Medium budget in Ind..."
7074,Rudra The Dhaba,1,New Delhi,77.306574,28.591447,north indian,200,No,No,No,1,0.0,0,India,north indian,Low,0.000000,0.00,0.000000,"Matched on north indian cuisine, Low budget in..."
4763,Creamy Creation,1,New Delhi,77.309698,28.623975,bakery,300,No,No,No,1,0.0,0,India,bakery,Medium,0.000000,0.00,0.000000,"Matched on bakery cuisine, Medium budget in In..."

In [30]:
df.to_csv("../data/sorted_df.csv", index=False)